after-login-command = []

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
# alt-enter = '''exec-and-forget osascript -e '
#     tell application "Terminal"
#         do script
#         activate
#     end tell'
#     '''

# alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
# alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
# alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
# alt-l = 'focus --boundaries-action wrap-around-the-workspace right'
ctrl-shift-h = 'focus left'
ctrl-shift-j = 'focus down'
ctrl-shift-k = 'focus up'
ctrl-shift-l = 'focus right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-b = 'balance-sizes'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-f = 'fullscreen'
alt-shift-t = 'layout floating tiling' # Toggle between floating and tiling layout

# alt-shift-s = 'split horizontal'
# alt-shift-v = 'split vertical'
#
# alt-s = 'layout v_accordion'               # 'layout stacking' in i3
# alt-w = 'layout h_accordion'               # 'layout tabbed' in i3
# alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-shift-n = 'workspace next'
ctrl-shift-p = 'workspace prev'

ctrl-shift-1 = 'workspace 1'
ctrl-shift-2 = 'workspace 2'
ctrl-shift-3 = 'workspace 3'
ctrl-shift-4 = 'workspace 4'
ctrl-shift-5 = 'workspace 5'
ctrl-shift-6 = 'workspace 6'
ctrl-shift-7 = 'workspace 7'
ctrl-shift-8 = 'workspace 8'
ctrl-shift-9 = 'workspace 9'
ctrl-shift-0 = 'workspace 10'
ctrl-shift-a = 'workspace a'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-a = 'move-node-to-workspace a'

alt-shift-n = 'move-node-to-workspace next'
alt-shift-p = 'move-node-to-workspace prev'

ctrl-shift-space = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
space = ['reload-config', 'mode main']
s = ['flatten-workspace-tree', 'mode main'] # reset layout

slash = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'

[workspace-to-monitor-force-assignment]
1 = ['built-in', 'main']
2 = ['built-in', 'main']
3 = ['built-in', 'main']
4 = ['built-in', 'main']
5 = ['dell u2723qe', 'dell u2412M', 'built-in', 'main']
6 = ['dell u2723qe', 'dell u2412M', 'built-in', 'main']
7 = ['dell u2723qe', 'dell u2412M', 'built-in', 'main']
8 = ['dell u2723qe', 'dell u2412M', 'built-in', 'main']
9 = ['dell u2724', 'dell u2415', 'built-in', 'main']
10 = ['dell u2724', 'dell u2415', 'built-in', 'main']
a = ['sidecar']

# 设置部分窗口默认为悬浮布局
# 可以使用 aerospace list-windows --all 命令查看窗口
# aerospace list-apps 查看app列表

# 默认将lark平铺布局
# [[on-window-detected]]
# if.app-id = "com.electron.lark"
# if.app-name-regex-substring = "Feishu"
# run = 'layout tiling'
#
# 默认将lark的工具浮动布局
# 包括图片预览
# [[on-window-detected]]
# if.app-id = "com.electron.lark.helper"
# run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Feishu'
run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'Feishu'
# # 匹配窗口标题
# if.window-title-regex-substring = 'Feishu'
# run = 'layout tiling'

# 将lark的搜索弹窗改为floating布局
# 怀疑是window-title为后置，因此此处不会生效
# [[on-window-detected]]
# if.app-name-regex-substring = 'Feishu'
# # 匹配窗口标题
# if.window-title-regex-substring = 'ModalWebViewWidget'
# run = 'layout floating'

# lark 图片预览 英文
[[on-window-detected]]
if.app-name-regex-substring = 'Lark Helper'
# 匹配窗口标题
if.window-title-regex-substring = 'Picture'
run = 'layout floating'

# lark 图片预览 中文
[[on-window-detected]]
if.app-name-regex-substring = 'Lark Helper'
# 匹配窗口标题
if.window-title-regex-substring = '图片'
run = 'layout floating'

# lark 屏幕录制播放 英文
[[on-window-detected]]
if.app-name-regex-substring = 'Lark Helper'
# 匹配窗口标题
if.window-title-regex-substring = 'Video player'
run = 'layout floating'

# lark 屏幕录制播放 中文
[[on-window-detected]]
if.app-name-regex-substring = 'Lark Helper'
# 匹配窗口标题
if.window-title-regex-substring = '视频播放器'
run = 'layout floating'

# lark 会议
[[on-window-detected]]
if.app-name-regex-substring = 'Feishu Meetings'
run = 'layout floating'

# lark 聊天记录
[[on-window-detected]]
if.app-name-regex-substring = 'Feishu'
if.window-title-regex-substring = 'chat between'
run = 'layout floating'

# lark 群聊记录
[[on-window-detected]]
if.app-name-regex-substring = 'Feishu'
if.window-title-regex-substring = 'group chat'
run = 'layout floating'

# lark 编辑日程
[[on-window-detected]]
if.app-name-regex-substring = 'Feishu'
if.window-title-regex-substring = 'Edit event'
run = 'layout floating'

# 汽水音乐
[[on-window-detected]]
if.app-name-regex-substring = '汽水音乐'
if.window-title-regex-substring = '汽水音乐'
run = 'layout floating'

# chrome task manager
[[on-window-detected]]
if.app-name-regex-substring = 'Google Chrome'
if.window-title-regex-substring = 'Task Manager'
run = 'layout floating'
